FactoryBot.define do
  factory :record do
    attributes {{
      id: 31938663,
      updated_at: "2015-04-30T12:36:24.081+12:00",
      created_at: "2013-05-01T11:20:23.215+12:00",
      title: "Title",
      description: "Setlist: 1. Watch the Corners 1:16 2. Crumble - 5:44 3. Training Ground - 9:50 4. SludgeFeast - 11:23 5. Out There - 17:04 6. Rude - 22:51 7. Pond Song - 26:05 Recorded at Roundhead Studios, Auckland, New Zealand Video: Hayden Booth, Meredith Rehburg. Audio: Troy Ferguson, Jordan Stone, w/ Jason Huss, Miranda Donovan.",
      content_partner: ["95bFM"],
      category: ["Videos"],
      creator: [],
      dc_type: [],
      dnz_type: "Unknown",
      date: [],
      source_url: "http://api.dnz0a.digitalnz.org/records/31938663/source",
      collection: ["YouTube"],
      alternate_title: [],
      additional_description: [],
      display_content_partner: "95bFM",
      collection_title: ["YouTube"],
      display_collection: "YouTube",
      primary_collection: ["YouTube"],
      contributing_partner: [],
      contributor: [],
      copyright: ["All rights reserved"],
      citation: [],
      credit_creator: nil,
      language: [],
      provenance: nil,
      publisher: [],
      rights: nil,
      usage: ["All rights reserved"],
      source: [],
      tag: [],
      thesis_level: nil,
      holding: [],
      library_collection: [],
      shelf_location: nil,
      eprints_type: [],
      text: nil,
      fulltext: nil,
      format: [],
      dc_identifier: [],
      display_date: "Unknown",
      published_date: [],
      syndication_date: "2013-05-01T11:20:23.215+12:00",
      landing_url: "https://www.youtube.com/watch?v=6aRQSZbFg1Q&feature=youtube_gdata_player",
      large_thumbnail_url: "https://i.ytimg.com/vi/6aRQSZbFg1Q/0.jpg",
      rights_url: [],
      thumbnail_url: "https://i.ytimg.com/vi/6aRQSZbFg1Q/default.jpg",
      origin_url: nil,
      metadata_url: nil,
      object_url: nil,
      has_version: [],
      license: nil,
      relation: [],
      is_part_of: [],
      is_replaced_by: nil,
      replaces: nil,
      is_required_by: nil,
      is_version_of: nil,
      table_of_contents: nil,
      is_commercial_use: nil,
      concept_ids: [],
      source_contributor_name: ['Culture', 'Europeana'],
      subject: ["Music"],
      locations: [
        {
          "placename" => "Miniginui",
          "_id" => '5749d0f8297b1f628a01e480',
          "comment" => 'Location provided by the Alexander Turnbull Library'
        },
        {
          "placename" => "Miniginui",
          "_id" => '5749d0f8297b1f628a01e481',
          "comment" => 'Location provided by the Alexander Turnbull Library'
        }
      ]
    }}

    trait :user_set do
      attributes {{
        id: 31938663,
        updated_at: "2015-04-30T12:36:24.081+12:00",
        created_at: "2013-05-01T11:20:23.215+12:00",
        title: "In Session: Dinosaur Jr. - Full Performance",
        description: "Setlist: 1. Watch the Corners 1:16 2. Crumble - 5:44 3. Training Ground - 9:50 4. SludgeFeast - 11:23 5. Out There - 17:04 6. Rude - 22:51 7. Pond Song - 26:05 Recorded at Roundhead Studios, Auckland, New Zealand Video: Hayden Booth, Meredith Rehburg. Audio: Troy Ferguson, Jordan Stone, w/ Jason Huss, Miranda Donovan.",
        content_partner: ["95bFM"],
        category: ["Sets"],
        creator: ['Jacinda'],
        dc_type: [],
        dnz_type: "Unknown",
        date: [],
        source_url: "http://api.dnz0a.digitalnz.org/records/31938663/source",
        collection: ["YouTube"],
        alternate_title: [],
        additional_description: [],
        display_content_partner: "95bFM",
        collection_title: ["YouTube"],
        display_collection: "YouTube",
        primary_collection: ["YouTube"],
        contributing_partner: [],
        contributor: [],
        copyright: ["All rights reserved"],
        citation: [],
        credit_creator: nil,
        language: [],
        provenance: nil,
        publisher: [],
        rights: nil,
        usage: ["All rights reserved"],
        source: [],
        tag: [],
        thesis_level: nil,
        holding: [],
        library_collection: [],
        shelf_location: nil,
        eprints_type: [],
        text: nil,
        fulltext: nil,
        format: ['Photograph'],
        dc_identifier: [],
        display_date: "Unknown",
        published_date: [],
        syndication_date: "2013-05-01T11:20:23.215+12:00",
        landing_url: "https://www.youtube.com/watch?v=6aRQSZbFg1Q&feature=youtube_gdata_player",
        large_thumbnail_url: "https://i.ytimg.com/vi/6aRQSZbFg1Q/0.jpg",
        rights_url: [],
        thumbnail_url: "https://i.ytimg.com/vi/6aRQSZbFg1Q/default.jpg",
        origin_url: nil,
        metadata_url: nil,
        object_url: nil,
        has_version: [],
        license: nil,
        relation: [],
        is_part_of: [],
        is_replaced_by: nil,
        replaces: nil,
        is_required_by: nil,
        is_version_of: nil,
        table_of_contents: nil,
        is_commercial_use: nil,
        concept_ids: [],
        source_contributor_name: ['Culture', 'Europeana'],
        subject: ["Music"],
        locations:  [
          {
            "placename" => "Miniginui",
            "_id" => '5749d0f8297b1f628a01e480',
            "comment" => 'Location provided by the Alexander Turnbull Library'
          },
          {
            "placename" => "Miniginui",
            "_id" => '5749d0f8297b1f628a01e481',
            "comment" => 'Location provided by the Alexander Turnbull Library'
          }
        ]
      }}
    end
  end
end
