language: ruby

addons:
  chrome: stable

services:
  - mysql

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_install:
  - gem install bundler --version $(tail -n 1 Gemfile.lock)
  - nvm install $(cat .nvmrc)

jobs:
  include:

    - stage: lint
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: lint
      name: 'Haml Lint'
      script:
        - bundle exec haml-lint app/**/*.html.haml

    - stage: lint
      name: 'Stylelint'
      script:
        - yarn install
        - ./node_modules/.bin/stylelint --color app/assets/stylesheets/**/*.scss

    - stage: test
      name: 'Unit tests'
      script:
        - RAILS_ENV=test bundle exec rails db:setup
        - bundle exec rspec
