language: ruby

addons:
  chrome: stable

services:
  - mysql

cache: bundler

jobs:
  include:

    - stage: lint
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'Unit tests'
      script:
        - RAILS_ENV=test bundle exec rails db:setup
        - bundle exec rspec
