language: ruby
rvm:
  - 2.3.0
install:
  - bundle install --jobs=3 --retry=3 --without production development --deployment
  - nvm install 5.5
  - nvm use 5.5
  - npm install
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rspec
  - cd client && node_modules/.bin/eslint .
cache: bundler
sudo: false
addons:
  code_climate:
    repo_token:
      secure: WRu+RLGOnbuoU7xsT3Mv84msGMHXq4mkMld1WU+UNtElbu5T5jjY/2TNA6NrN5rZSHvzAM0+UiDXu5yalXyyDX0Ww5EaLRfYdLmYFxRb89plM71d3h66OxtLRIO0cF/Au5kp9OUOBszeXHd5R7mugl9l53e8DrEjoQC6Vry6E/8=
notifications:
  slack:
    secure: i9U1oP2ApD0u4qrLvpauQr+WSlt6fjo5KHI1UOiabGb5i1fKHCcSm71TOvrOmGybFmqP25D15rnBRDL3j4BgOoM1JCtx2Wm1YDCWmLh0Hgvib9P2UPkfqP9/n4UJxkUhLwuoxJjH5vLXAxlP3KguBWrTJOsuo8NA9sCItl0wVL4=
