sudo: required

language: ruby

stages:
- lint
- test

addons:
  chrome: stable

services:
  - mysql
  - yarn

cache: bundler

jobs:
include:
  - stage: lint
    script:
      - rubocop
  - stage: test
    install:
      - RAILS_ENV=test bin/rails db:setup
    script:
      - bundle exec rspec
