sudo: required

language: ruby

stages:
- lint
- test

addons:
  chrome: stable

cache: bundler

jobs:
include:
  - stage: lint
    script:
      - rubocop
  - stage: test
    script:
      - bundle exec rspec
